export const ACTION = {
  ADD_FIRST_TABLE_NUMBER: 'ADD_FIRST_TABLE_NUMBER',
  ADD_SECOND_TABLE_NUMBER: 'ADD_SECOND_TABLE_NUMBER',
  DEL_FIRST_TABLE_NUMBER: 'DEL_FIRST_TABLE_NUMBER',
  DEL_SECOND_TABLE_NUMBER: 'DEL_SECOND_TABLE_NUMBER',
}